### ISSUE TITLE
您好，请问WinUI3的SwapChainPanel可以用来播放视频吗？如果可以的话，需要做哪些工作呢~

### ISSUE THREAD

**Issue by FrancisKoo** [TienAska/HelloWinUI#1]

**Comment by TienAska** [comment]
SwapChainPanel是承接DirectX的framebuffer用的，可以用dx的视频解码api处理视频

**Comment by FrancisKoo** [comment]
感谢您的回复！如果封装视频处理类的话，必须要是runtime类吗，普通类可以吗

**Comment by TienAska** [comment]
这个就不清楚了，我也才接触

**Comment by FrancisKoo** [comment]
我正在看您使用WinUI3开发的WhiteFlint 项目。注意到您封装了一个dll处理SwapChainPnel的render。如果直接在desktop内封装render可以吗~

**Comment by TienAska** [comment]
可以的，winui3只要提供hwnd给d3d就行了

**Comment by FrancisKoo** [comment]
非常感谢您的回复~
